import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const DYLAN_EMAIL="dylan.sprouse@unifiedtitle.net";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}})}
function publishableKey(){return Deno.env.get("SUPABASE_PUBLISHABLE_KEY")||Deno.env.get("SUPABASE_ANON_KEY")||""}
async function userFor(req:Request){const auth=req.headers.get("Authorization"),url=Deno.env.get("SUPABASE_URL"),key=publishableKey();if(!auth||!url||!key)return null;const r=await fetch(`${url}/auth/v1/user`,{headers:{Authorization:auth,apikey:key}});return r.ok?await r.json():null}
const STOP=new Set(["the","and","for","with","from","that","this","into","onto","about","check","checking","remind","reminder","todo","task","came","come","received","receive","arrived","arrive","still","open","tomorrow","today","morning","afternoon","evening","later","whether","been","have","has","had","are","was","were","will","would","should","could","need","needs","needed","call","callback","follow","followup"]);
function norm(v:any){return String(v||"").toLowerCase().replace(/['’]s\b/g,"").replace(/[^a-z0-9]+/g," ").trim()}
function words(v:any){return new Set(norm(v).split(" ").filter(x=>x.length>2&&!STOP.has(x)))}
function similar(a:any,b:any,dueA?:any,dueB?:any){const A=words(a),B=words(b);if(!A.size||!B.size)return false;let same=0;for(const x of A)if(B.has(x))same++;if(same<2)return false;const containment=same/Math.min(A.size,B.size),union=new Set([...A,...B]).size,jaccard=same/union;if(containment>=.8)return true;if(String(dueA||"")&&String(dueA)===String(dueB||"")&&containment>=.6)return true;return jaccard>=.65}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return json({error:"Method not allowed."},405);const user=await userFor(req);if(!user||String(user.email||"").toLowerCase()!==DYLAN_EMAIL)return json({error:"Dylan authentication is required."},403);let p:any;try{p=await req.json()}catch{return json({error:"A JSON body is required."},400)}const actions=Array.isArray(p.actions)?p.actions.slice(0,10):[],caseNumber=String(p.case_number||"").trim();const url=Deno.env.get("SUPABASE_URL"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!service)return json({error:"Duplicate check service is not configured."},503);const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const [{data:caseRows},{data:todos},{data:calls}]=await Promise.all([admin.from("title_search_cases").select("case_number,payload").eq("case_number",caseNumber).is("deleted_at",null).limit(1),admin.from("dylan_voice_todos").select("title,due_date,due_text").eq("user_id",user.id).eq("completed",false).is("deleted_at",null),admin.from("dylan_call_records").select("payload").eq("user_id",user.id).is("deleted_at",null)]);const payload=caseRows?.[0]?.payload||{};const results=actions.map((a:any)=>{let kind:string|null=null,detail:string|null=null;const type=String(a.action_type||""),text=String(a.text||""),due=a.due_date||null;if(type==="add_case_note"&&text){const notes=String(payload.notes||"");if(norm(notes).includes(norm(text))||similar(notes,text)){kind="Similar case note already exists";detail=text}}
else if(type==="update_next_step"&&text&&similar(payload.nextAction||"",text)){kind="Next step already appears to be set";detail=String(payload.nextAction||text)}
else if(type==="create_todo"){const hit=(todos||[]).find((t:any)=>norm(t.title)===norm(text)||similar(t.title,text,t.due_date,due));if(hit){kind="Similar open to-do already exists";detail=String(hit.title)+(hit.due_date?` · due ${hit.due_date}`:"")}}
else if(type==="create_callback"){const contact=norm(a.contact_name||""),num=norm(caseNumber);const hit=(calls||[]).find((r:any)=>{const q=r.payload||{},open=String(q.status||q.followStatus||"").toLowerCase()!=="completed",sameContact=contact&&norm(q.caller||"")===contact,sameFile=norm(q.fileNumber||"")===num,sameTopic=similar(q.nextAction||q.task||q.subject||"",text,q.dueDate,due);return open&&sameFile&&sameContact&&(sameTopic||!String(q.nextAction||q.task||q.subject||"").trim())});if(hit){const q=hit.payload||{};kind="Open callback already exists";detail=String(q.caller||"Existing callback")+(q.nextAction?` · ${q.nextAction}`:"")}}
return {duplicate_found:Boolean(kind),duplicate_kind:kind,duplicate_detail:detail}});return json({results})});
